import { useFonts } from 'expo-font';
import {
    Poppins_100Thin,
    Poppins_100Thin_Italic,
    Poppins_200ExtraLight,
    Poppins_200ExtraLight_Italic,
    Poppins_300Light,
    Poppins_300Light_Italic,
    Poppins_400Regular,
    Poppins_400Regular_Italic,
    Poppins_500Medium,
    Poppins_500Medium_Italic,
    Poppins_600SemiBold,
    Poppins_600SemiBold_Italic,
    Poppins_700Bold,
    Poppins_700Bold_Italic,
    Poppins_800ExtraBold,
    Poppins_800ExtraBold_Italic,
    Poppins_900Black,
    Poppins_900Black_Italic,
} from '@expo-google-fonts/poppins';
import {
    DMSans_100Thin,
    DMSans_100Thin_Italic,
    DMSans_200ExtraLight,
    DMSans_200ExtraLight_Italic,
    DMSans_300Light,
    DMSans_300Light_Italic,
    DMSans_400Regular,
    DMSans_400Regular_Italic,
    DMSans_500Medium,
    DMSans_500Medium_Italic,
    DMSans_600SemiBold,
    DMSans_600SemiBold_Italic,
    DMSans_700Bold,
    DMSans_700Bold_Italic,
    DMSans_800ExtraBold,
    DMSans_800ExtraBold_Italic,
    DMSans_900Black,
    DMSans_900Black_Italic,
} from '@expo-google-fonts/dm-sans';

export function useFontsLoader() {
    const [fontsLoaded] = useFonts({
        // Poppins
        'Poppins-Thin': Poppins_100Thin,
        'Poppins-ThinItalic': Poppins_100Thin_Italic,
        'Poppins-ExtraLight': Poppins_200ExtraLight,
        'Poppins-ExtraLightItalic': Poppins_200ExtraLight_Italic,
        'Poppins-Light': Poppins_300Light,
        'Poppins-LightItalic': Poppins_300Light_Italic,
        'Poppins-Regular': Poppins_400Regular,
        'Poppins-Italic': Poppins_400Regular_Italic,
        'Poppins-Medium': Poppins_500Medium,
        'Poppins-MediumItalic': Poppins_500Medium_Italic,
        'Poppins-SemiBold': Poppins_600SemiBold,
        'Poppins-SemiBoldItalic': Poppins_600SemiBold_Italic,
        'Poppins-Bold': Poppins_700Bold,
        'Poppins-BoldItalic': Poppins_700Bold_Italic,
        'Poppins-ExtraBold': Poppins_800ExtraBold,
        'Poppins-ExtraBoldItalic': Poppins_800ExtraBold_Italic,
        'Poppins-Black': Poppins_900Black,
        'Poppins-BlackItalic': Poppins_900Black_Italic,

        // DM Sans
        'DMSans-Thin': DMSans_100Thin,
        'DMSans-ThinItalic': DMSans_100Thin_Italic,
        'DMSans-ExtraLight': DMSans_200ExtraLight,
        'DMSans-ExtraLightItalic': DMSans_200ExtraLight_Italic,
        'DMSans-Light': DMSans_300Light,
        'DMSans-LightItalic': DMSans_300Light_Italic,
        'DMSans-Regular': DMSans_400Regular,
        'DMSans-Italic': DMSans_400Regular_Italic,
        'DMSans-Medium': DMSans_500Medium,
        'DMSans-MediumItalic': DMSans_500Medium_Italic,
        'DMSans-SemiBold': DMSans_600SemiBold,
        'DMSans-SemiBoldItalic': DMSans_600SemiBold_Italic,
        'DMSans-Bold': DMSans_700Bold,
        'DMSans-BoldItalic': DMSans_700Bold_Italic,
        'DMSans-ExtraBold': DMSans_800ExtraBold,
        'DMSans-ExtraBoldItalic': DMSans_800ExtraBold_Italic,
        'DMSans-Black': DMSans_900Black,
        'DMSans-BlackItalic': DMSans_900Black_Italic,
    });

    return fontsLoaded;
}